swagger: '2.0'
info:
  description: This is a boggle solver API
  version: 1.0.0
  title: Boggle Solver API
  # put the contact info for your development or API team
  contact:
    email: nsinghvi@umich.edu

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

paths:
  /solve-boggle:
    post:
      summary: takes a picture and attempts to play boggle on the board
      operationId: solveBoggle
      produces:
        - application/json
      parameters:
        - name: boggleBoard
          in: body
          description: "A 2d array representing boggle boards"
          required: true
          schema:
            $ref: '#/definitions/BoggleBoard'
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              type: string
        400:
          description: bad input parameter
  /get-boggle-board:
    post:
      summary: takes in a file (picture of boggle board and returns a 2d array boggle board)
      operationID: getBoggleBoard
      produces:
        -application/json
      parameters:
        - name: fileName
          in:
          description: "A file with a picture of the boggle Board"
          required: true
          schema:
            $ref: '#/definitions/fileName'
      responses:
        200:
          description: returns a boggle board
          schema:
            type: array
            items:
              type: string
        400:
          description: bad input parameter
definitions:
  BoggleBoard:
    type: array
    items:
      type: array
      items:
        type: string
  FileName:
    type: string
    items:

schemes:
  - https