openapi: 3.0.0
info:
  description: This is a boggle solver API
  version: 1.0.0-oas3
  title: Boggle Solver API
  contact:
    email: nsinghvi@umich.edu
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /solve-boggle:
    post:
      summary: returns the valid words for a 2d array representing a boggle board
      operationId: solveBoggle
      requestBody:
        description: A 2d array represnting boggle boards
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BoggleBoard'
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '400':
          description: bad input parameter
  /get-boggle-board:
    post:
      summary: takes in a file (picture of boggle board and returns a 2d array boggle board
      operationId: getBoggleBoard
      requestBody: 
        content: 
          multipart/form-data:
            schema: 
              type: object
              properties: 
                fileName:
                  type: string
                  format: binary
      responses:
        200:
          description: returns a boggle board
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BoggleBoard'
        400:
          description: bad input parameter
components:
  schemas:
    BoggleWord:
      type: object
      properties:
        word:
          type: string
    BoggleBoard:
      type: array
      items:
        type: array
        items:
          type: string