/* tslint:disable */
/* eslint-disable */
/**
 * Boggle Solver API
 * This is a boggle solver API
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * Contact: nsinghvi@umich.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BoggleWord
 */
export interface BoggleWord {
    /**
     * 
     * @type {string}
     * @memberof BoggleWord
     */
    word?: string;
}

export function BoggleWordFromJSON(json: any): BoggleWord {
    return BoggleWordFromJSONTyped(json, false);
}

export function BoggleWordFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoggleWord {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'word': !exists(json, 'word') ? undefined : json['word'],
    };
}

export function BoggleWordToJSON(value?: BoggleWord | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'word': value.word,
    };
}


